steps:
  # --- Étape 1: Validation Terraform ---
  - name: 'hashicorp/terraform:1.3.7'
    id: 'Terraform Validate'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        echo "Validating Terraform configuration..."
        cd terraform
        terraform init -backend-config=bucket=${_TF_STATE_BUCKET}
        terraform validate
        echo "Terraform validation successful."

  # --- Étape 2: Setup Python Env & Install Dependencies ---
  # Crée un venv dans /workspace et installe les dépendances dedans
  - name: 'python:3.11'
    id: 'Setup Python Environment'
    entrypoint: 'bash' # bash pour pouvoir chainer les commandes
    args:
      - '-c'
      - |
        echo "Creating virtual environment in /workspace/venv..."
        python -m venv /workspace/venv
        echo "Installing dependencies into venv..."
        # pip du venv pour installer
        /workspace/venv/bin/pip install --upgrade pip
        /workspace/venv/bin/pip install -r src/cloud_function_ingest/requirements.txt -r requirements-dev.txt
        echo "Dependencies installed."

  # --- Étape 3: Linting du code Python ---
  # Utilise l'exécutable flake8 DEPUIS le venv créé à l'étape précédente
  - name: 'python:3.11' 
    id: 'Lint Cloud Function Code'
    entrypoint: '/workspace/venv/bin/flake8' # Chemin complet vers flake8 dans le venv
    args: ['src/cloud_function_ingest/']

  # --- Étape 4: Exécution des Tests Unitaires Python ---
  # Utilise l'exécutable pytest DEPUIS le venv
  - name: 'python:3.11'
    id: 'Run Cloud Function Unit Tests'
    entrypoint: '/workspace/venv/bin/pytest' # Chemin complet vers pytest dans le venv
    args: ['src/cloud_function_ingest/tests/']


# Options globales pour le build
options:
  logging: CLOUD_LOGGING_ONLY

# Configuration du timeout global (optionnel)
# timeout: "1200s" # 20 minutes