steps:
  # --- Étape 1: Validation Terraform ---
  # (vérifier la syntaxe de l'infra)
  - name: 'hashicorp/terraform:1.3.7'
    id: 'Terraform Validate'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        echo "Validating Terraform configuration..."
        cd terraform # Se placer dans le dossier Terraform
        terraform init -backend-config=bucket=${_TF_STATE_BUCKET} # Utilise la variable de substitution du trigger
        terraform validate
        echo "Terraform validation successful."

  # --- Étape 2: Installation des dépendances Python ---
  # Installe les libs nécessaires pour la fonction ET pour les tests/linting
  - name: 'python:3.11' 
    id: 'Install Python Dependencies'
    entrypoint: pip
    args: [
        'install',
        '-r', 'src/cloud_function_ingest/requirements.txt', # Dépendances de la fonction
        '-r', 'requirements.txt' # Dépendances de dev (flake8, pytest)
      ]

  # --- Étape 3: Linting du code Python ---
  # Vérifie la qualité/style du code de la Cloud Function
  - name: 'python:3.11'
    id: 'Lint Cloud Function Code'
    entrypoint: python 
    args: [
        '-m',         
        'flake8',     
        'src/cloud_function_ingest/' 
      ]

  # --- Étape 4: Exécution des Tests Unitaires Python ---
  # Lance les tests définis dans le dossier tests/ de la fonction
  - name: 'python:3.11'
    id: 'Run Cloud Function Unit Tests'
    entrypoint: python
    args: [
        '-m',      
        'pytest',  
        'src/cloud_function_ingest/tests/' # Chemin vers les tests
      ]

# Options globales pour le build
options:
  logging: CLOUD_LOGGING_ONLY # option pour les logs

# Configuration du timeout global
# timeout: "1200s" # 20 minutes